package com.yu.db.dao;

import java.util.ArrayList;

import com.yu.db.model.StorageServer;

public interface StorageServerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table storage_server
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table storage_server
	 *
	 * @mbggenerated
	 */
	int insert(StorageServer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table storage_server
	 *
	 * @mbggenerated
	 */
	StorageServer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table storage_server
	 *
	 * @mbggenerated
	 */
	int updateByName(StorageServer ss);
	
	/**
	 * 查找一个已开启的并且大小超过一定值的一个存储服务器
	 * @param limit
	 * @return
	 */
	ArrayList<StorageServer> getStorageServerBySizeLimit(long limit);
	
	/**
	 * 根据名字查找存储服务器
	 * @param name
	 * @return
	 */
	StorageServer selectStorageServerByName(String name);

}