package com.yu.db.model;

public class SFile {

	private int backStorageServerId;

	private String backFullName;

	public String getBackFullName() {
		return backFullName;
	}

	public void setBackFullName(String backFullName) {
		this.backFullName = backFullName;
	}

	private String fullName;

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column file.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column file.uuid
	 *
	 * @mbggenerated
	 */
	private String uuid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column file.storage_server_id
	 *
	 * @mbggenerated
	 */
	private Integer storageServerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column file.size
	 *
	 * @mbggenerated
	 */
	private int size;

	public SFile() {
	}

	public SFile(String fullName, String name, String uuid,
			Integer storageServerId, int size, int backStorageServerId,
			String backFullName) {
		super();
		this.fullName = fullName;
		this.name = name;
		this.uuid = uuid;
		this.storageServerId = storageServerId;
		this.size = size;
		this.backFullName = backFullName;
		this.backStorageServerId = backStorageServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column file.name
	 *
	 * @return the value of file.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column file.name
	 *
	 * @param name
	 *            the value for file.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column file.uuid
	 *
	 * @return the value of file.uuid
	 *
	 * @mbggenerated
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column file.uuid
	 *
	 * @param uuid
	 *            the value for file.uuid
	 *
	 * @mbggenerated
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid == null ? null : uuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column file.storage_server_id
	 *
	 * @return the value of file.storage_server_id
	 *
	 * @mbggenerated
	 */
	public Integer getStorageServerId() {
		return storageServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column file.storage_server_id
	 *
	 * @param storageServerId
	 *            the value for file.storage_server_id
	 *
	 * @mbggenerated
	 */
	public void setStorageServerId(Integer storageServerId) {
		this.storageServerId = storageServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column file.size
	 *
	 * @return the value of file.size
	 *
	 * @mbggenerated
	 */
	public int getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column file.size
	 *
	 * @param size
	 *            the value for file.size
	 *
	 * @mbggenerated
	 */
	public void setSize(int size) {
		this.size = size;
	}

	@Override
	public String toString() {
		return "SFile [backStorageServerId=" + backStorageServerId
				+ ", backFullName=" + backFullName + ", fullName=" + fullName
				+ ", name=" + name + ", uuid=" + uuid + ", storageServerId="
				+ storageServerId + ", size=" + size + "]";
	}

	public int getBackStorageServerId() {
		return backStorageServerId;
	}

	public void setBackStorageServerId(int backStorageServerId) {
		this.backStorageServerId = backStorageServerId;
	}

}